---
- hosts: all
  become: true
  vars:
    intellij_install_root: /home/vagrant/install/intellij
    intellij_version: ideaIC-171.3691.12
    intellij_tar_name: "{{ intellij_version }}-no-jdk"
    activemq_install_root: /home/vagrant/install/activemq
    activemq_version: apache-activemq-5.14.4
  tasks:
     - name: Load aptitude
       apt: name=aptitude state=present

     - name: Update apt-cache 
       apt: update_cache=yes cache_valid_time=3600

#     - name: Update apt-cache 
#       apt: upgrade=yes

     - name: Install Vim
       apt: name=vim state=latest
       
#     - name: Upgrade and then update packages on box
#       apt: upgrade=yes update_cache=yes cache_valid_time=3600
     - name: Install java 8 preresequesits
       apt: name=python-software-properties

     - name: Add Java 8 repository
       apt_repository: repo='ppa:webupd8team/java'

     - name: Agree to oracle license
       debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

     - name: Install Java 8
       apt: name=oracle-java8-installer force=yes
       
     - name: Creates Intellij install directory
       file: path={{ intellij_install_root }} state=directory
  
     - name: unpack the intellij installation archive
       unarchive: src=/vagrant/files/install/intellij/{{ intellij_tar_name }}.tar.gz dest={{ intellij_install_root }} 
         remote_src=yes mode=0777 group=vagrant owner=vagrant
         
     - name: getunpacked name
       find:
         paths: "{{ intellij_install_root }}"
         patterns: "idea*"
         file_type: "directory"
       register: filelist
#     - debug: 
#         msg: "filelist: {{ filelist }}"
         
     - name: set symlink to keep path to intellij constant (error if more than one intellij)
       file:
         src: "{{ item.path }}"
         dest: "{{ intellij_install_root }}/idea"
         state: link
         force: yes
       with_items: "{{ filelist.files }}" 

     - name: set desktop icon
       file:
         src: /vagrant/files/desktop/shortcut/jetbrains-idea-ce.desktop
         dest: /home/vagrant/.local/share/applications
         mode: 0600
       
     - name: set locale
       file:
         src: /vagrant/files/locale/locale
         dest: /etc/default
         owner: root
         group: root
         mode: 0644
        
#     - name: set keyboard layout
#       shell: gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'gb'), ('xkb', 'us')]"
#       args:
#         executable: /bin/bash
     - name: Remove old profile
       file: path=/home/vagrant/.profile state=absent
       
     - name: copy over profile
       copy:
         src: /vagrant/files/profile/.profile
         dest: /home/vagrant/.profile
         owner: vagrant
         group: vagrant
         mode: 0644
       
     - name: Create activemq install directory
       file: path={{ activemq_install_root }} state=directory
  
     - name: unpack the activemq installation archive
       unarchive: src=/vagrant/files/install/activemq/{{ activemq_version }}-bin.tar.gz dest={{ activemq_install_root }} 
         remote_src=yes mode=0777 group=vagrant owner=vagrant
 
     - name: set symlink to keep path to activemq constant
       file:
         src: "{{ activemq_install_root }}/{{ activemq_version }}"
         dest: "{{ activemq_install_root }}/activemq"
         state: link
         force: yes
         
     - name: set startup script for activemq
       template:
         src: /vagrant/files/templates/start-active-mq.sh.j2
         dest: "{{ activemq_install_root }}/start-active-mq.sh"
         owner: vagrant
         group: vagrant
         mode: 0744
 
     
